<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.quyq.gwsu</groupId>
        <artifactId>root-pom</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>business</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>application</module>
        <module>business-security</module>
        <module>business-system</module>
        <module>business-log</module>
        <module>business-kit</module>
        <module>business-headless</module>
    </modules>


    <dependencies>
        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-core</artifactId>
        </dependency>
    </dependencies>


</project>
