spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gwsu}
          username: ${DB_USERNAME:root}
          password: ${DB_PASSWORD:root}
          driver-class-name: org.postgresql.Driver
#        mysql:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/gwsu?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#          username: root
#          password: root