[request_definition]
r = sub, res_type, act, url, env

[policy_definition]
p = sub, res_type, act, url, env_cond, eft

[matchers]
m = (p.sub == "*" || r.sub == p.sub) && (p.res_type == "*" || r.res_type == p.res_type) && (p.act == "*" || r.act == p.act) && keyMatch2(r.url, p.url) && eval(p.env_cond)

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))