<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.quyq.gwsu</groupId>
        <artifactId>business-headless</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>business-headless-server</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>business-headless-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-database</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-cache</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-ai</artifactId>
        </dependency>

        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>${playwright.version}</version>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>business-kit-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jcodec</groupId>
            <artifactId>jcodec</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jcodec</groupId>
            <artifactId>jcodec-javase</artifactId>
        </dependency>


    </dependencies>

</project>
