<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.quyq.gwsu</groupId>
    <artifactId>project-pom</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>


    <properties>
        <project.version>1.0-SNAPSHOT</project.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-deploy</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-database</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-cache</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-security</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-authentication</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-ai</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>common-log</artifactId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>business-security-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>business-security-server</artifactId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>business-system-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.quyq.gwsu</groupId>
                <artifactId>business-system-server</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>



</project>