package org.quyq.gwsu.common.ai.agui.event;

/**
 * AG-UI 事件类型。
 *
 * @author Quyq
 * @date 2026/7/27
 */
public enum AguiEventType {
    RUN_STARTED,
    RUN_FINISHED,
    TEXT_MESSAGE_START,
    TEXT_MESSAGE_CONTENT,
    TEXT_MESSAGE_END,
    TOOL_CALL_START,
    TOOL_CALL_ARGS,
    TOOL_CALL_END,
    TOOL_CALL_RESULT,
    STATE_SNAPSHOT,
    STATE_DELTA,
    RAW,
    CUSTOM,
    REASONING_START,
    REASONING_MESSAGE_START,
    REASONING_MESSAGE_CONTENT,
    REASONING_MESSAGE_END,
    REASONING_MESSAGE_CHUNK,
    REASONING_END
}
